/*
 * YouTub Project Original (2026)
 * arslandaim-hub (GitHub.com/arslandaim-hub)
 * Licenced Under GPL-3.0+
*/
package com.youtub.ui.components

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.slideInVertically
import androidx.compose.animation.slideOutVertically
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.media3.common.Player
import androidx.media3.common.text.Cue
import androidx.media3.common.text.CueGroup
import com.youtub.utils.PTLog

@Composable
fun Media3SubtitleOverlay(
    player: Player?,
    enabled: Boolean,
    modifier: Modifier = Modifier,
    isAutoGenerated: Boolean = false,
    fontSizeSp: Float = 16f,
    backgroundOpacity: Float = 0.65f,
    bottomPaddingDp: Float = 48f
) {
    var cues by remember { mutableStateOf(emptyList<Cue>()) }

    DisposableEffect(player) {
        if (player == null) {
            onDispose { }
        } else {
            val listener = object : Player.Listener {
                override fun onCues(cueGroup: CueGroup) {
                    cues = cueGroup.cues
                    if (cues.isNotEmpty()) {
                        PTLog.d("Media3SubtitleOverlay", "Received ${cues.size} cues. First: ${cues.first().text}")
                    }
                }
            }
            player.addListener(listener)
            cues = player.currentCues.cues
            onDispose {
                player.removeListener(listener)
            }
        }
    }

    val displayText = remember(enabled, isAutoGenerated, cues) {
        if (!enabled) null else cues.toSubtitleDisplayText(isAutoGenerated)
    }

    AnimatedVisibility(
        visible = displayText != null,
        enter = fadeIn() + slideInVertically { it / 2 },
        exit = fadeOut() + slideOutVertically { it / 2 },
        modifier = modifier.fillMaxSize()
    ) {
        if (displayText != null) {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(horizontal = 16.dp),
                contentAlignment = Alignment.BottomCenter
            ) {
                Surface(
                    color = Color.Black.copy(alpha = backgroundOpacity),
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier.offset(y = (-bottomPaddingDp).dp)
                ) {
                    Text(
                        text = displayText,
                        color = Color.White,
                        fontSize = fontSizeSp.sp,
                        fontWeight = FontWeight.Medium,
                        textAlign = TextAlign.Center,
                        lineHeight = (fontSizeSp * 1.25f).sp,
                        modifier = Modifier.padding(horizontal = 12.dp, vertical = 6.dp)
                    )
                }
            }
        }
    }
}

private fun List<Cue>.toSubtitleDisplayText(isAutoGenerated: Boolean): String? {
    if (isEmpty()) return null
    
    val textCues = mapNotNull { it.text?.toString()?.cleanCueText(isAutoGenerated) }
        .filter { it.isNotBlank() }
        .distinct()

    if (textCues.isEmpty()) {
        // If we have cues but no text, it might be an image cue or empty timing cue
        return null
    }
    
    // Join all distinct cues with a newline. 
    // This ensures we don't miss text when subtitles are split into multiple cues.
    val result = textCues.joinToString("\n").trim()
    
    return result.ifBlank { null }
}

private fun String.cleanCueText(isAutoGenerated: Boolean): String {
    val lines = replace('\u00A0', ' ')
        .replace(Regex("[ \\t\\x0B\\f\\r]+"), " ")
        .lines()
        .map { it.trim() }
        .filter { it.isNotBlank() }

    if (lines.isEmpty()) return ""
    if (isAutoGenerated) return lines.latestRollingCaptionLine()

    return lines.takeLast(2).joinToString("\n").trim()
}

private fun List<String>.latestRollingCaptionLine(): String {
    if (size == 1) return first()
    val latestLine = last()
    val previousLine = this[size - 2]
    val previousWords = previousLine.splitWords()
    val latestWords = latestLine.splitWords()

    if (previousWords.isEmpty() || latestWords.isEmpty()) return latestLine
    val overlap = longestSuffixPrefixOverlap(previousWords, latestWords)
    val freshWords = latestWords.drop(overlap)

    return freshWords.takeIf { it.isNotEmpty() }?.joinToString(" ") ?: latestLine
}

private fun String.splitWords(): List<String> = split(Regex("\\s+")).filter { it.isNotBlank() }

private fun longestSuffixPrefixOverlap(previous: List<String>, latest: List<String>): Int {
    val maxOverlap = minOf(previous.size, latest.size)
    for (count in maxOverlap downTo 1) {
        val prevSuffix = previous.takeLast(count)
        val latestPrefix = latest.take(count)
        if (prevSuffix.indices.all { i -> prevSuffix[i].trimPunctuation().equals(latestPrefix[i].trimPunctuation(), ignoreCase = true) }) {
            return count
        }
    }
    return 0
}

private fun String.trimPunctuation(): String = trim { !it.isLetterOrDigit() }
