/*
 * YouTub Project Original (2026)
 * arslandaim-hub (GitHub.com/arslandaim-hub)
 * Licenced Under GPL-3.0+
*/
package com.youtub.ui.screens.player

import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.MimeTypes
import androidx.media3.common.Player
import androidx.media3.common.TrackSelectionOverride
import androidx.media3.common.util.UnstableApi
import com.youtub.domain.model.StreamBundle
import com.youtub.domain.model.SubtitleItem
import java.util.Locale
import javax.inject.Inject

@UnstableApi
class PlayerTrackManager @Inject constructor() {

    fun updateCcState(player: Player, enabled: Boolean, preferredLang: String?) {
        val parametersBuilder = player.trackSelectionParameters.buildUpon()
        
        if (enabled) {
            parametersBuilder.setTrackTypeDisabled(C.TRACK_TYPE_TEXT, false)
            
            if (preferredLang != null) {
                parametersBuilder.setPreferredTextLanguage(preferredLang)
                parametersBuilder.clearOverridesOfType(C.TRACK_TYPE_TEXT)
            }
            
            val currentTracks = player.currentTracks
            val hasActiveTextTrack = currentTracks.groups.any { it.type == C.TRACK_TYPE_TEXT && it.isSelected }
            
            if (!hasActiveTextTrack) {
                for (group in currentTracks.groups) {
                    if (group.type == C.TRACK_TYPE_TEXT && group.isSupported) {
                        parametersBuilder.addOverride(
                            TrackSelectionOverride(group.mediaTrackGroup, 0)
                        )
                        break
                    }
                }
            }
        } else {
            parametersBuilder.setTrackTypeDisabled(C.TRACK_TYPE_TEXT, true)
            parametersBuilder.clearOverridesOfType(C.TRACK_TYPE_TEXT)
        }
        
        player.trackSelectionParameters = parametersBuilder.build()
    }

    fun createSubtitleConfigs(bundle: StreamBundle): List<MediaItem.SubtitleConfiguration> {
        return bundle.subtitles.filter { it.url.isNotBlank() }.map { subtitle ->
            val mimeType = when (subtitle.format.lowercase()) {
                "vtt" -> MimeTypes.TEXT_VTT
                "ttml" -> MimeTypes.APPLICATION_TTML
                "srt" -> MimeTypes.APPLICATION_SUBRIP
                else -> MimeTypes.TEXT_VTT
            }
            
            val label = if (subtitle.isAutoGenerated) {
                "${Locale.forLanguageTag(subtitle.languageTag).displayLanguage} (Auto-generated)"
            } else {
                Locale.forLanguageTag(subtitle.languageTag).displayLanguage
            }

            MediaItem.SubtitleConfiguration.Builder(android.net.Uri.parse(subtitle.url))
                .setMimeType(mimeType)
                .setLanguage(subtitle.languageTag)
                .setLabel(label)
                .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
                .build()
        }
    }
}
